theme: jekyll-theme-slate
name: Daniel Vaughan
markdown: kramdown
highlighter: rouge
default_lang: csharp
encoding: utf-8
repository: DVaughan/DVaughan.github.io
paginate: 5
paginate_path: "/blog/page:num/"
gems: 
 - [jekyll-paginate]
 - jekyll-sitemap
 - jekyll-redirect-from
 - jekyll-feed
permalink: /posts/:categories/:year/:month/:day/:title/
excerpt_separator: '<a name="excerpt-end"></a>'